# Generated by Django 3.2.4 on 2021-06-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210612_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['message_date']},
        ),
    ]
