# Generated by Django 3.2.4 on 2021-06-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-message_date']},
        ),
    ]
