# Generated by Django 3.2.4 on 2021-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ManyToManyField(to='chat.Room'),
        ),
    ]
